// Single source of truth for the read-only denylist.
// Imported by index.js (runtime Proxy) and tools/oxlint/wa-readonly (lint rule).
// Add a method here and both enforcement layers pick it up.
export const MUTATING_METHODS = [
  "sendMessage",
  "sendReceipt",
  "sendReceipts",
  "readMessages",
  "chatModify",
  "sendPresenceUpdate",
  "presenceSubscribe",
  "updateProfileStatus",
  "updateProfileName",
  "updateProfilePicture",
  "removeProfilePicture",
  "fetchPrivacySettings",
  "updateBlockStatus",
  "updateLastSeenPrivacy",
  "updateOnlinePrivacy",
  "updateReadReceiptsPrivacy",
  "updateGroupsAddPrivacy",
  "updateDefaultDisappearingMode",
  "groupCreate",
  "groupLeave",
  "groupUpdateSubject",
  "groupUpdateDescription",
  "groupParticipantsUpdate",
  "groupSettingUpdate",
  "groupInviteCode",
  "groupRevokeInvite",
  "groupAcceptInvite",
  "groupGetInviteInfo",
  "newsletterCreate",
  "newsletterUpdate",
  "newsletterDelete",
  "newsletterReact",
  "newsletterFollow",
  "newsletterUnfollow",
  "newsletterMute",
  "newsletterUnmute",
  "logout",
  "requestPairingCode",
];
